version: '2.2'
services:
  db:
    image: postgres:10.1-alpine
    container_name: song-hub-db
    environment:
      POSTGRES_USER: song_hub
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    networks:
      - shnet
  adminer:
    image: adminer
    container_name: song-hub-adminer
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - shnet

networks:
  shnet:
