default: &default
  adapter: postgresql
  encoding: unicode
  username: song_hub
  password: secret
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: song_hub_development

test:
  <<: *default
  database: song_hub_test

production:
  <<: *default
  database: song_hub_production
